### ISSUE TITLE
morph运行错误，“不支持该请求”

### ISSUE THREAD

**Issue by ench4nt3r** [walkerfuz/morph#1]
调用栈如下：

```
Connected to pydev debugger (build 162.1967.10)

            __________              ____  __    __
           /  __  __  \____  ____  / __ \/ /   / /
          /  / / / /  / __ \/  __\/ /_/ / /___/ /
         /  / / / /  / /_/ /  /  /  ___/  ___  /
         \_/  \/  \_/\____/\_/   \_/   \_/  /_/

  By Walkerfuz of Taurus Security(https://github.com/walkerfuz)
                                          Morph - Version 0.3.1

[+R+]: Waiting web server power on...
Process Process-2:
(-2147024846, '不支持该请求。', (None, None, None, 0, None))
Traceback (most recent call last):
  File "D:\Program Files (x86)\python3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\python3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files (x86)\morph-master\node\morph.py", line 52, in pre_fuzz
    crashInfo = Debugger.Run(sample_proc.encode(), False, mode)
  File "D:\Program Files (x86)\python3\lib\site-packages\pydbgeng3-0.0.2-py3.5.egg\PyDbgEng3\Debugger.py", line 62, in Run
    raise e
  File "D:\Program Files (x86)\python3\lib\site-packages\pydbgeng3-0.0.2-py3.5.egg\PyDbgEng3\Debugger.py", line 55, in Run
    dbg_eng_dll_path = DbgEngDllPath)
  File "D:\Program Files (x86)\python3\lib\site-packages\pydbgeng3-0.0.2-py3.5.egg\PyDbgEng3\PyDbgEng\ProcessCreator.py", line 33, in __init__
    self.idebug_client.CreateProcess(Server=UserModeSession.NO_PROCESS_SERVER, CommandLine = command_line, CreateFlags = creation_flags)
_ctypes.COMError: (-2147024846, '不支持该请求。', (None, None, None, 0, None))
Process Process-3:
```

请问这该如何解决？

**Comment by ench4nt3r** [comment]
@walkerfuz 方便留个企鹅吗？有些关于nduja的问题想讨教一下，比如在`fuzzAttributes`函数中，有用到`currentNode`，这个变量的赋值时由`nodeIteration`完成，但是这个函数并没有任何人调用它，是不是还有什么其他技巧使得`nodeIteration`被调用啊？

**Comment by walkerfuz** [comment]
企鹅不怎么用。公布的nduja只是原作者写的fuzz脚本，`fuzzAttributes`函数没有调用，有可能是作者故意省略了。其实能看懂nduja源码的话，自己写出来更强大的fuzz逻辑就行。

**Comment by walkerfuz** [comment]
安装出现上述问题，应该是comtypes库导致的。请确认自己以前是否安装过comtypes库，如果安装，请删除并从github上下载罪行的comtypes库，并删除旧版库生成的下列缓存：
`Python\Lib\site-packages\comtypes\gen\`
`c:\Users\%USERNAME%\AppData\Local\Temp\comtypes_cache\ directory`
我最新的测试环境可用：
`Win10` `Python3.5.3` `tornado-4.4.2` `psutil-5.1.3` `comtypes 1.1.3` `Visual C++ Redistributable 2012 ` `PyDbgEng3 0.0.3`

**Comment by walkerfuz** [comment]
目前正在优化Morph架构，并支持一键安装，夏天尽快发布。若有问题，请发邮件给我。
